#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 [test set]"
    exit 1
fi

LABEL="$1"
FOLDER=$LABEL

if ! [[ -e llvm2c ]]; then
    echo "llvm2c not found!"
    exit 1
fi

echo "Running $LABEL tests..."

FAILED=0
TEMPDIR=`mktemp -d`
for f in inputs/$FOLDER/*.c; do
    echo "Testing $f"
    clang "$f" -o $TEMPDIR/orig 2>/dev/null
    clang "$f" -emit-llvm -S -Xclang -disable-O0-optnone -o $TEMPDIR/temp.ll #2>/dev/null
    ./llvm2c $TEMPDIR/temp.ll --o $TEMPDIR/temp.c # >> /dev/null
    if [[ $? != 0 ]]; then
        echo -e "\t[NOK] llvm2c failed to translate $f!"
        FAILED=$((FAILED+1))
    else
        clang $TEMPDIR/temp.c -o $TEMPDIR/new 2>/dev/null
        if [[ $? != 0 ]]; then
            echo -e "\t[NOK] Clang could not compile translated file $f!"
            FAILED=$((FAILED+1))
        else
          if ! diff -y --suppress-common-lines expected/$FOLDER/$(basename $f) $TEMPDIR/temp.c; then
            echo -e "\t[NOK] Translated C file is different than expected"
            FAILED=$((FAILED+1))
          else
            echo -e "\t[OK ] Files are equal"
          fi
        fi
    fi
    rm -rf $TEMPDIR/*
done

rm -rf $TEMPDIR

if [[ $FAILED -eq 0 ]]; then
    echo "All $LABEL tests passed!"
else
    echo "$FAILED $LABEL tests failed!"
fi

exit $FAILED
