#!/bin/bash

if ! [[ -e llvm2c ]]; then
	echo "llvm2c not found!"
	exit 1
fi

LABEL="phi"
FOLDER=$LABEL

echo "Running $LABEL tests..."

BR=0

for f in $FOLDER/*.c; do
	clang "$f" -o orig 2>/dev/null
	clang "$f" -emit-llvm -S -Xclang -disable-O0-optnone -o temp.ll #2>/dev/null
    opt -mem2reg -o temp2.ll -S temp.ll
    [ -f temp2.ll ] || exit 1
    mv temp2.ll temp.ll
	./llvm2c temp.ll --o temp.c # >> /dev/null
	if [[ $? != 0 ]]; then
		echo "llvm2c failed to translate $f!"
		BR=$((BR+1))
	else
		clang temp.c -o new 2>/dev/null
		if [[ $? != 0 ]]; then
			echo "Clang could not compile translated file $f!"
			BR=$((BR+1))
		else

			for i in `seq -10 10`; do
				./orig $i
				ORIG=$?
				./new $i
                NEW=$?
				if [[ $ORIG != $NEW ]]; then
					echo "Test $f failed with input $i!"
					BR=$((BR+1))
				fi
			done

		fi
	fi
    rm -f orig new temp.ll temp.c
done

if [[ $BR -eq 0 ]]; then
	echo "All $LABEL tests passed!"
else
	echo "$BR $LABEL tests failed!"
fi
