#!/bin/bash

if ! [[ -e llvm2c ]]; then
    echo "llvm2c not found!"
    exit 1
fi

echo "Updating expected test results..."

TEMPDIR=`mktemp -d`

for FOLDER in `ls inputs`; do
    for f in inputs/$FOLDER/*.c; do

        clang "$f" -o $TEMPDIR/orig 2>/dev/null
        clang "$f" -emit-llvm -S -Xclang -disable-O0-optnone -o $TEMPDIR/temp.ll #2>/dev/null
        if [[ $FOLDER = "phi" ]]; then
            opt -mem2reg $TEMPDIR/temp.ll -o $TEMPDIR/temp.ll
        fi

        if ! ./llvm2c ${TEMPDIR}/temp.ll --o expected/${FOLDER}/`basename $f`; then
          echo "Paused. Press enter to continue"
          echo "$TEMPDIR"
          read
        fi

        echo "Update $f"
        rm $TEMPDIR/*
    done
done

rm -rf $TEMPDIR
